#
# Copyright (C) 2025 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# ######################################################################################################################
# crun shared library (system-provided)
# ######################################################################################################################

find_library(LIBCRUN_SO NAMES crun PATHS /usr/local/lib REQUIRED)

add_library(crun::crun SHARED IMPORTED GLOBAL)
set_target_properties(
    crun::crun
    PROPERTIES IMPORTED_LOCATION             ${LIBCRUN_SO}
               INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_CURRENT_SOURCE_DIR}
)

# ######################################################################################################################
# Target name
# ######################################################################################################################

set(TARGET_NAME container)

# ######################################################################################################################
# Sources
# ######################################################################################################################

set(SOURCES
    config.cpp
    container.cpp
    filesystem.cpp
    instance.cpp
    monitoring.cpp
    crunhandler.cpp
    runner.cpp
    runtimeconfig.cpp
)

# ######################################################################################################################
# Libraries
# ######################################################################################################################

set(LIBRARIES Poco::JSON aos::common::utils aos::sm::runtimes::utils aos::sm::utils crun::crun)

# ######################################################################################################################
# Target
# ######################################################################################################################

add_module(
    TARGET_NAME
    ${TARGET_NAME}
    LOG_MODULE
    STACK_USAGE
    ${AOS_STACK_USAGE}
    SOURCES
    ${SOURCES}
    HEADERS
    ${HEADERS}
    LIBRARIES
    ${LIBRARIES}
)

# ######################################################################################################################
# Tests
# ######################################################################################################################

if(WITH_TEST)
    add_subdirectory(tests)
endif()
